unit TestUMainLog;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, CodeSiteLogging, SysUtils, UMainLog, UMainConstant, Vcl.Dialogs;

type
  // Test methods for class MainLog

  TestMainLog = class(TTestCase)
  strict private
    FMainLog: MainLog;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCodeSiteDestination;
  end;

implementation

procedure TestMainLog.SetUp;
begin
  FMainLog := MainLog.Create;
end;

procedure TestMainLog.TearDown;
begin
  FMainLog.Free;
  FMainLog := nil;
end;

procedure TestMainLog.TestCodeSiteDestination;
var
  ReturnValue: TCodeSiteDestination;
begin
  ReturnValue := FMainLog.CodeSiteDestination;
  // TODO: CheckTrue
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestMainLog.Suite);
end.

