unit TestUIp;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, UIp;

type
  // Test methods for class ip

  Testip = class(TTestCase)
  strict private
    Fip: ip;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestLoad1;
    procedure TestLoad2;
  end;

implementation

procedure Testip.SetUp;
begin
  Fip := ip.Create;
end;

procedure Testip.TearDown;
begin
  Fip.Free;
  Fip := nil;
end;

procedure Testip.TestLoad1;
var
  oneLineLog: string;
begin
  oneLineLog := Fip.load
    ('193.200.150.152 - - [17/Jan/2015:10:52:28 +0600] "GET /irbis64r_01/js/script.js HTTP/1.0" 200 838');
  CheckEquals(oneLineLog, '193.200.150.152', oneLineLog);

end;

procedure Testip.TestLoad2;
var
  oneLineLog: string;
begin
  oneLineLog := Fip.load
    ('178.63.68.137 - - [17/Jan/2015:10:57:05 +0600] "GET /irbis64r_01/css/jquery.autocomplete.css HTTP/1.1" 200 921');
  CheckEquals(oneLineLog, '178.63.68.137', oneLineLog);
end;

initialization

// Register any test cases with the test runner
RegisterTest(Testip.Suite);

end.
